### ISSUE TITLE
DownloadAvatar() returns null URL and no avatar

### ISSUE THREAD

**Issue by reithegoat** [InfectedBytes/gj-unity-api#30]
I was attempting to download the current user's avatar but after trying to get the URL and replacing a sprite with the avatar, the sprite remains unchanged and the URL returns with "Object reference not set to an instance of an object.".

**Comment by InfectedBytes** [comment]
Have you tried the UI Demo scene? It contains an example for downloading an avatar.
Besides from that, when and how do you call the download avatar method? The SignIn method has two callbacks, the first one is called when the sign in has completed and the second one is called when the user information was fetched (for example the avatar url). So when you try to download the avatar from the first callback, the AvatarUrl is not yet fetched.
Here is a simple example:
```
var user = new User(username, token);
user.SignIn(null, success => user.DownloadAvatar(s => myImage.sprite = user.Avatar));
```

**Comment by reithegoat** [comment]
The example managed to help.
