### ISSUE TITLE
UnityEngine.Networking.UnityWebRequest.GetTexture(string)' is obsolete On Unity 2017.4.2f

### ISSUE THREAD

**Issue by Robinaite** [InfectedBytes/gj-unity-api#34]
Hey there,

After importing it cleanly into an empty project I get the following error that the method above is obsolete and should be updated.
https://i.imgur.com/ffGz2Hw.png
Found in GameJoltApi file at line 95 using Unity 2017.4.2f
Won't allow me to do anything till I change it as suggested.

**Comment by InfectedBytes** [comment]
yeah, Unity has changed the API for it, but at least for newer versions of Unity (I've used 2018.1), the updater automatically changes it.
But of course, I'll fix this directly from code by adding a corresponding `#if UNITY_2017_1_OR_NEWER`, so you don't have to change anything :)

**Comment by Robinaite** [comment]
Just wanted to be sure, you didn't forget! 👍 Good work on it! Yeah for Unity 2017, it also gives a notice that there's outdated API stuff and with one click it can be upgradable, but it upgrades everything and doesn't let you choose.

**Comment by InfectedBytes** [comment]
fixed, I also added an `#if UNITY...` around the `request.Send` part, because in newer versions one should use `request.SendWebRequest`. 
Please let me know if you find anything else 😄
