### ISSUE TITLE
Application.ExternalEval is deprecated

### ISSUE THREAD

**Issue by loicteixeira** [InfectedBytes/gj-unity-api#37]
Initially [reported by RobinHoodPT](https://gamejolt.com/f/unity-api-v2/12745?page=6#forum-post-447658).

Using Unity `2018.2.10f` (and presumably the WebGL build) throw a deprecation warning about `Application.ExternalEval`. The documentation lists some [alternatives](https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html).

**Comment by InfectedBytes** [comment]
~~TODO: switch to jslib files~~
edit: actually it is not even necessary to call javascript code, because we can access the webgl url parameters via Application.absoluteURL 😄
