### ISSUE TITLE
SettingsEditor Console Error

### ISSUE THREAD

**Issue by hypermonkey1** [InfectedBytes/gj-unity-api#41]
![error](https://user-images.githubusercontent.com/49995224/67108774-e001fc80-f1d7-11e9-8991-73d1cc5c386d.PNG)

I'm getting this error in my version 2018.3.14f1
in vanilla asset

**Comment by InfectedBytes** [comment]
hmmm, no problem with 2018.3.0f2.
Have you restarted Unity?
You could also try to do a "Reimport all" (this may take a while, depending on your project size)
