### ISSUE TITLE
[GJ Unity API v2.5.4] Recieving a variety of errors on build in unity 2019.1.6f1 

### ISSUE THREAD

**Issue by neon-gr33n** [InfectedBytes/gj-unity-api#44]
![window](https://user-images.githubusercontent.com/41244356/71104984-c145c500-218a-11ea-8d2d-c957d203fed8.PNG)

**Comment by InfectedBytes** [comment]
just go to "Plugins/Editor/ GameJolt/GameJolt/GameJoltEditor.asmdef" make sure that in the inspector under the "Platforms" area the "Any Platform" is *not* checked and directly below it (under "Include Platforms") only "Editor" is checked. Afterwards click on apply.
I'll fix this in package and upload it soon.

**Comment by neon-gr33n** [comment]
> just go to "Plugins/Editor/ GameJolt/GameJolt/GameJoltEditor.asmdef" make sure that in the inspector under the "Platforms" area the "Any Platform" is _not_ checked and directly below it (under "Include Platforms") only "Editor" is checked. Afterwards click on apply.
> I'll fix this in package and upload it soon.

thank you so much! it seems to be working now, it built without the errors too!
