### ISSUE TITLE
user avatar

### ISSUE THREAD

**Issue by fgsoftware1** [InfectedBytes/gj-unity-api#49]
how i can get and set a user avatar in a image object?

**Comment by InfectedBytes** [comment]
Have a look at the UI demo scene of this package.
Basically you just need to call Download avatar on your user object and when the callback is called you can set the image. for e.g.:
```
GameJoltAPI.Instance.CurrentUser.DownloadAvatar(success => {
  if(success) {
    image.sprite = GameJoltAPI.Instance.CurrentUser.Avatar;
  }
}));
```

**Comment by fgsoftware1** [comment]
i seen this but i lost it.
thanks for reply.
