### ISSUE TITLE
leaderbord

### ISSUE THREAD

**Issue by fgsoftware1** [InfectedBytes/gj-unity-api#50]
im getting this error when i add score on leaderboard 

`You must enter a score.
UnityEngine.Debug:LogWarning (object)
GameJolt.API.LogHelper:Warning (string,object[]) (at Assets/Plugins/GameJolt/Scripts/API/LogHelper.cs:32)
GameJolt.API.Core.Response:.ctor (UnityEngine.Networking.UnityWebRequest,GameJolt.API.Core.ResponseFormat) (at Assets/Plugins/GameJolt/Scripts/API/Core/Response.cs:118)
GameJolt.API.GameJoltAPI/<GetRequest>d__17:MoveNext () (at Assets/Plugins/GameJolt/Scripts/API/GameJoltAPI.cs:108)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)`

**Comment by InfectedBytes** [comment]
well, as the error says: you must enter a score... 😉 
GameJolt requires you to enter a numeric score value (used for actual sorting/ranking) and also a textual representation of that score, which is shown on GameJolt.
So I guess you just did something like: `Scores.Add(value, "")`, but the string must not be empty, so instead you should do:
`Scores.Add(value, value.ToString())`
or `Scores.Add(value, $"{value} Points")`

**Comment by fgsoftware1** [comment]
> well, as the error says: you must enter a score... 😉 GameJolt requires you to enter a numeric score value (used for actual sorting/ranking) and also a textual representation of that score, which is shown on GameJolt. So I guess you just did something like: `Scores.Add(value, "")`, but the string must not be empty, so instead you should do: `Scores.Add(value, value.ToString())` or `Scores.Add(value, $"{value} Points")`

i made this 

`Scores.Add(score, scoreText.text, 656734);`

i already try to do 

`Scores.Add(score, score.text, 656734);`

656734 - is a table id

**Comment by InfectedBytes** [comment]
I guess scoreText.text is simply empty

**Comment by fgsoftware1** [comment]
i made this on Update

`scoreText.text = "score: " + score;`

im doing this on trigger

`score = score + 1;`

**Comment by InfectedBytes** [comment]
put a debug output right before you call `Scores.Add` to see what's actually used:
```
Debug.Log(scoreText.text);
Scores.Add(Score, scoreText.text, 656734);
```

**Comment by fgsoftware1** [comment]
> put a debug output right before you call `Scores.Add` to see what's actually used:
> 
> ```
> Debug.Log(scoreText.text);
> Scores.Add(Score, scoreText.text, 656734);
> ```

don't appear anything on console

**Comment by fgsoftware1** [comment]
allright i figured out the error was on trigger

**Comment by fgsoftware1** [comment]
thanks for your help anyway

**Comment by InfectedBytes** [comment]
yeah no problem, you're welcome
