### ISSUE TITLE
Why is TryUnlockResult not working?

### ISSUE THREAD

**Issue by FiveNights21611** [InfectedBytes/gj-unity-api#53]
I'm trying to implement a trophy into my game, but it keeps saying TryUnlockResult doesn't exist. I looked into the trophies script, it exists there. What do I do?

**Comment by InfectedBytes** [comment]
could you post the surrounding code?

**Comment by FiveNights21611** [comment]
I fixed it. 

I had to add "GameJolt.Api." in front of each instance of the TryUnlockResult in the code to unlock a trophy, and it works now! It was a weird fix, but it worked.

**Comment by InfectedBytes** [comment]
you just didn't add the using directive.
That's a namespace and you should simply import it:
```
using GameJolt.API; // at the top
// and then you can just use it like:
GameJoltAPI .TryUnlockTrophy(...)
```
